version: "3.2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
      target: app
    image: app:0.1.0
    container_name: app
    ports:
      - "8501:8501"
    volumes:
      - ./app/run:/app/run
      - mecabdic:/var/lib/mecab/dic
    restart: always
    command: streamlit run main.py

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.simple
      target: jupyter
    image: jupyter:0.1.0
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/jupyter/notebooks
      - mecabdic:/var/lib/mecab/dic
    restart: always
    command: jupyter lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''
  # Keep dictionary data persistent
volumes:
  mecabdic:
    name: mecab-dic
